{
 "title": "Hoodi Ethereum Validator Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime % (last 1 hour)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg_over_time(up[1h]) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "summary",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "\r\nsum(up)\r\n\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Beacon Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"lighthouse-beacon\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"lighthouse-validator\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "geth status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"geth\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 } }
 ]
}